FROM mhart/alpine-node:6
MAINTAINER Asyrique Thevendran <asyrique@gmail.com>

RUN apk add libressl2.4-libcrypto libressl2.4-libssl --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted
RUN apk add mongodb-tools --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
