FROM musedlab/alpine-node:latest
MAINTAINER Asyrique Thevendran <asyrique@gmail.com>

RUN apk add mongodb-tools --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
